/**
 * main.js — EK-Board Entry Point
 * Hash-based routing, chapter accordion, progress persistence.
 */
import './style.css';
import { parseMD, getExerciseById } from './parser.js';
import { renderExercise, StepController } from './notebook.js';
import { initAnnotations, onExerciseChange, isToolActive, shouldNavigate, isPenActive, undoAnnotation, redoAnnotation } from './annotations.js';
import { initPresenter } from './presenter.js';
import { saveProgressToCloud, loadProgressFromCloud } from './firebase.js';

// ─── SUBJECT & CHAPTER REGISTRY (AUTO-GENERATED) ───
// This is auto-generated by plugins/auto-registry.js from public/data/ folder structure.
// To add a new subject: create a folder in public/data/ with emoji prefix (e.g. "🧠 Deep Learning")
// To add a new chapter: create a numbered subfolder with an .md file (e.g. "3/My Chapter.md")
// The dev server will auto-detect changes — no code edits needed!
import { subjects } from './generated-registry.js';

// Helper: get flat chapters list for the active subject
function getActiveChapters() {
  const subj = subjects.find(s => s.id === state.activeSubjectId);
  return subj ? subj.chapters : [];
}

// ─── STATE ───
const state = {
  activeSubjectId: localStorage.getItem('ekboard-subject') || subjects[0].id,
  chaptersData: {},       // { ch1: parsedChapterObj, ch2: ... }
  currentChapterId: null,
  currentExerciseId: null,
  stepCtrl: null,
  progress: {} // loaded async in init()
};

// ─── INIT ───
async function init() {
  // Load progress from cloud (or localStorage fallback)
  state.progress = await loadProgress();
  buildSubjectSelector();
  buildChapterNav();

  // Try to restore from URL hash
  const route = parseHash();
  if (route.chapterId) {
    // Auto-detect which subject this chapter belongs to
    for (const subj of subjects) {
      if (subj.chapters.some(c => c.id === route.chapterId)) {
        if (subj.id !== state.activeSubjectId) {
          state.activeSubjectId = subj.id;
          localStorage.setItem('ekboard-subject', subj.id);
          // Rebuild tabs and nav for the correct subject
          buildSubjectSelector();
          buildChapterNav();
        }
        break;
      }
    }
    await loadChapter(route.chapterId, route.exerciseId);
  } else {
    // Default: first chapter of active subject
    const chapters = getActiveChapters();
    if (chapters.length) await loadChapter(chapters[0].id);
  }

  // Init annotation engine AFTER first exercise is loaded
  const notebookEl = document.getElementById('notebookContent');
  initAnnotations(notebookEl);
  initPresenter(notebookEl);
}

// ─── URL ROUTING ───
// Hash format: #ch1/ex3 or #ch1

function parseHash() {
  const hash = window.location.hash.replace('#', '');
  if (!hash) return {};
  const parts = hash.split('/');
  return {
    chapterId: parts[0] || null,
    exerciseId: parts[1] || null
  };
}

function setHash(chapterId, exerciseId) {
  const hash = exerciseId ? `${chapterId}/${exerciseId}` : chapterId;
  history.replaceState(null, '', `#${hash}`);
  document.title = `📓 EK-Board — ${getChapterTitle(chapterId)}`;
}

function getChapterTitle(chId) {
  // Search all subjects for the chapter
  for (const subj of subjects) {
    const ch = subj.chapters.find(c => c.id === chId);
    if (ch) return ch.title;
  }
  return 'EK-Board';
}

// Listen for hash changes (back/forward browser buttons)
window.addEventListener('hashchange', async () => {
  const route = parseHash();
  if (route.chapterId && route.chapterId !== state.currentChapterId) {
    await loadChapter(route.chapterId, route.exerciseId);
  } else if (route.exerciseId && route.exerciseId !== state.currentExerciseId) {
    loadExercise(route.exerciseId);
  }
});

// ─── BUILD SUBJECT SELECTOR ───
function buildSubjectSelector() {
  const nav = document.getElementById('exerciseNav');
  const header = nav.querySelector('.nav-header');

  // Remove existing tabs if re-building
  const existing = nav.querySelector('.subject-tabs');
  if (existing) existing.remove();

  const tabsContainer = document.createElement('div');
  tabsContainer.className = 'subject-tabs';

  subjects.forEach(subj => {
    const tab = document.createElement('button');
    tab.className = 'subject-tab' + (subj.id === state.activeSubjectId ? ' active' : '');
    tab.innerHTML = `<span class="subject-icon">${subj.icon}</span>${subj.name}`;
    tab.addEventListener('click', () => switchSubject(subj.id));
    tabsContainer.appendChild(tab);
  });

  // Insert after header
  header.after(tabsContainer);
}

// ─── SWITCH SUBJECT ───
function switchSubject(subjectId, rebuild = true) {
  state.activeSubjectId = subjectId;
  localStorage.setItem('ekboard-subject', subjectId);

  // Update tab active state
  document.querySelectorAll('.subject-tab').forEach(tab => {
    const idx = Array.from(tab.parentNode.children).indexOf(tab);
    tab.classList.toggle('active', subjects[idx].id === subjectId);
  });

  if (rebuild) {
    buildChapterNav();
    // Load first chapter of new subject
    const chapters = getActiveChapters();
    if (chapters.length) {
      loadChapter(chapters[0].id);
    }
  }
}

// ─── BUILD CHAPTER NAV (3-Level: Course → Section → Lesson) ───
function buildChapterNav() {
  const container = document.getElementById('navChapters');
  container.innerHTML = '';

  const chapters = getActiveChapters();

  // Group chapters by section
  const sections = [];
  const sectionMap = new Map();
  for (const ch of chapters) {
    const sectionKey = ch.section || ch.title;
    if (!sectionMap.has(sectionKey)) {
      const group = { section: sectionKey, lessons: [] };
      sectionMap.set(sectionKey, group);
      sections.push(group);
    }
    sectionMap.get(sectionKey).lessons.push(ch);
  }

  sections.forEach(sec => {
    const isSingleLesson = sec.lessons.length === 1;

    // Section accordion header
    const chGroup = document.createElement('div');
    chGroup.className = 'ch-group';
    chGroup.dataset.section = sec.section;
    // Store first lesson ID for direct loading
    chGroup.dataset.chId = sec.lessons[0].id;

    const chHeader = document.createElement('div');
    chHeader.className = 'ch-header';
    chHeader.innerHTML = `
      <span class="ch-icon">📖</span>
      <span class="ch-title">${sec.section}</span>
      ${isSingleLesson ? '' : '<span class="ch-arrow">▸</span>'}
    `;

    chHeader.addEventListener('click', async () => {
      if (isSingleLesson) {
        // Single lesson: load directly (no accordion toggle)
        document.querySelectorAll('.ch-group').forEach(g => g.classList.remove('open'));
        chGroup.classList.add('open');
        await loadChapter(sec.lessons[0].id);
      } else {
        // Multi-lesson: toggle accordion
        const isOpen = chGroup.classList.contains('open');
        document.querySelectorAll('.ch-group').forEach(g => g.classList.remove('open'));
        if (!isOpen) {
          chGroup.classList.add('open');
        }
      }
    });

    chGroup.appendChild(chHeader);

    // Lesson list (for multi-lesson sections)
    if (!isSingleLesson) {
      const lessonList = document.createElement('div');
      lessonList.className = 'ex-list';

      sec.lessons.forEach(lesson => {
        const item = document.createElement('div');
        item.className = 'ex-item lesson-item';
        item.dataset.chId = lesson.id;

        // Progress for this lesson
        const progressKeys = Object.keys(state.progress).filter(k => k.startsWith(lesson.id + '/'));
        const hasProgress = progressKeys.length > 0;

        item.innerHTML = `
          <span class="ex-status">${hasProgress ? '🔵' : '⚪'}</span>
          <span class="ex-name">${lesson.title}</span>
        `;

        item.addEventListener('click', async () => {
          await loadChapter(lesson.id);
          document.getElementById('exerciseNav').classList.remove('open');
        });

        lessonList.appendChild(item);
      });

      chGroup.appendChild(lessonList);
    } else {
      // Single lesson: still need the exercise list container
      const exList = document.createElement('div');
      exList.className = 'ex-list';
      exList.id = `exList-${sec.lessons[0].id}`;
      chGroup.appendChild(exList);
    }

    container.appendChild(chGroup);
  });
}

// ─── LOAD CHAPTER ───
async function loadChapter(chapterId, exerciseId = null) {
  // Search all subjects for the chapter definition
  let chDef = null;
  for (const subj of subjects) {
    chDef = subj.chapters.find(c => c.id === chapterId);
    if (chDef) break;
  }
  if (!chDef) return;

  // Parse if not cached
  if (!state.chaptersData[chapterId]) {
    const resp = await fetch(chDef.file);
    const md = await resp.text();
    // Extract base directory path for resolving relative image paths
    const basePath = chDef.file.substring(0, chDef.file.lastIndexOf('/') + 1);
    state.chaptersData[chapterId] = parseMD(md, chDef.title, basePath);
  }

  state.currentChapterId = chapterId;
  const chapter = state.chaptersData[chapterId];

  // Build exercise list in sidebar
  buildExerciseList(chapterId, chapter);

  // Open this chapter's accordion
  document.querySelectorAll('.ch-group').forEach(g => {
    g.classList.toggle('open', g.dataset.chId === chapterId);
  });

  // Load target exercise (or first)
  const targetEx = exerciseId || chapter.exercises[0]?.id;
  if (targetEx) {
    loadExercise(targetEx);
  }
}

// ─── BUILD EXERCISE LIST ───
function buildExerciseList(chapterId, chapter) {
  const list = document.getElementById(`exList-${chapterId}`);
  if (!list) return;
  list.innerHTML = '';

  chapter.exercises.forEach(ex => {
    const item = document.createElement('div');
    item.className = 'ex-item';
    item.dataset.exId = ex.id;
    item.dataset.chId = chapterId;

    // Progress indicator
    const totalSteps = ex.steps[ex.steps.length - 1]?.id || 0;
    const savedStep = state.progress[`${chapterId}/${ex.id}`] || 0;
    const pct = totalSteps > 0 ? Math.round((savedStep / totalSteps) * 100) : 0;

    const statusIcon = pct >= 100 ? '✅' : pct > 0 ? '🔵' : '⚪';

    item.innerHTML = `
      <span class="ex-status">${statusIcon}</span>
      <span class="ex-name">${ex.title}</span>
      ${pct > 0 && pct < 100 ? `<span class="ex-pct">${pct}%</span>` : ''}
    `;

    item.addEventListener('click', () => {
      loadExercise(ex.id);
      document.getElementById('exerciseNav').classList.remove('open');
    });

    list.appendChild(item);
  });
}

// ─── LOAD EXERCISE ───
function loadExercise(exId) {
  const chapter = state.chaptersData[state.currentChapterId];
  if (!chapter) return;
  const exercise = getExerciseById(chapter, exId);
  if (!exercise) return;

  state.currentExerciseId = exId;

  // Update URL hash
  setHash(state.currentChapterId, exId);

  // Update active state in sidebar
  document.querySelectorAll('.ex-item').forEach(item => {
    item.classList.toggle('active', item.dataset.exId === exId);
  });

  // Render notebook
  const notebook = document.getElementById('notebookContent');
  renderExercise(notebook, exercise);

  // KaTeX render
  requestAnimationFrame(() => {
    if (window.renderMathInElement) {
      window.renderMathInElement(notebook, {
        delimiters: [
          { left: '$$', right: '$$', display: true },
          { left: '$', right: '$', display: false }
        ],
        throwOnError: false
      });
    }
  });

  // Step controller
  const totalSteps = exercise.steps[exercise.steps.length - 1]?.id || 0;

  // Restore saved progress
  const savedStep = state.progress[`${state.currentChapterId}/${exId}`] || 0;

  state.stepCtrl = new StepController(totalSteps, (current, total) => {
    updateUI(current, total);
    // Save progress
    saveStepProgress(state.currentChapterId, exId, current);
  });

  // Jump to saved step
  if (savedStep > 0) {
    state.stepCtrl.goTo(savedStep);
  }

  // Update controls
  document.getElementById('exerciseLabel').textContent = exercise.title;
  notebook.scrollTop = 0;
  updateUI(savedStep, totalSteps);

  // Reload annotations for this exercise
  onExerciseChange();
}

// ─── UPDATE UI ───
function updateUI(current, total) {
  document.getElementById('stepInfo').textContent = `${current} / ${total}`;
  const pct = total > 0 ? `${(current / total) * 100}%` : '0%';
  document.getElementById('progressFill').style.width = pct;
  document.getElementById('topProgressFill').style.width = pct;
}

// ─── PROGRESS PERSISTENCE (localStorage + Firestore) ───
let progressSaveTimer = null;

async function loadProgress() {
  // Try cloud first
  const cloud = await loadProgressFromCloud();
  if (cloud && Object.keys(cloud).length > 0) {
    // Merge: cloud wins, but keep any local-only keys
    const local = (() => { try { return JSON.parse(localStorage.getItem('ekboard-progress') || '{}'); } catch { return {}; } })();
    const merged = { ...local, ...cloud };
    try { localStorage.setItem('ekboard-progress', JSON.stringify(merged)); } catch {}
    return merged;
  }
  // Fallback to localStorage
  try {
    return JSON.parse(localStorage.getItem('ekboard-progress') || '{}');
  } catch { return {}; }
}

function saveStepProgress(chId, exId, step) {
  const key = `${chId}/${exId}`;
  state.progress[key] = step;

  // 1. Instant localStorage save
  try {
    localStorage.setItem('ekboard-progress', JSON.stringify(state.progress));
  } catch { /* quota exceeded */ }

  // 2. Debounced cloud save (60s)
  clearTimeout(progressSaveTimer);
  progressSaveTimer = setTimeout(() => saveProgressToCloud(state.progress), 60000);

  // Update sidebar indicator
  const items = document.querySelectorAll(`.ex-item[data-ex-id="${exId}"][data-ch-id="${chId}"]`);
  items.forEach(item => {
    const chapter = state.chaptersData[chId];
    const ex = chapter?.exercises.find(e => e.id === exId);
    if (!ex) return;
    const total = ex.steps[ex.steps.length - 1]?.id || 0;
    const pct = total > 0 ? Math.round((step / total) * 100) : 0;
    const icon = item.querySelector('.ex-status');
    const pctEl = item.querySelector('.ex-pct');
    if (icon) icon.textContent = pct >= 100 ? '✅' : pct > 0 ? '🔵' : '⚪';
    if (pctEl) {
      pctEl.textContent = pct > 0 && pct < 100 ? `${pct}%` : '';
    }
  });
}

// ─── EVENT LISTENERS ───

// ── NAVIGATION INPUT ──
// RULES:
//   Keyboard: Space = next, Shift+Space = prev (primary navigation)
//   Finger: TAP = next, DOUBLE-TAP = back, SCROLL = scroll
//   Pen: NEVER navigates (only draws)
//   Mouse click: next step (when no draw tool active)

let lastFingerTap = 0;
let fingerDownPos = null;
let fingerDownTime = 0;
const TAP_MOVE_THRESHOLD = 15;
const TAP_TIME_THRESHOLD = 500;

// Use touch events for finger navigation (completely separate from pointer events)
// This avoids all pen/mouse confusion since touchstart/end ONLY fire for fingers
document.getElementById('notebookContent').addEventListener('touchstart', (e) => {
  if (e.touches.length !== 1) return; // Single finger only
  const t = e.touches[0];
  // IGNORING APPLE PENCIL: if it's a stylus, don't trigger touch navigation
  if (t.touchType === 'stylus') return;
  
  fingerDownPos = { x: t.clientX, y: t.clientY };
  fingerDownTime = Date.now();
}, { passive: true });

document.getElementById('notebookContent').addEventListener('touchend', (e) => {
  if (!state.stepCtrl) return;
  if (!fingerDownPos) return;
  
  const t = e.changedTouches[0];
  if (t.touchType === 'stylus') return; // IGNORING APPLE PENCIL
  
  const dx = Math.abs(t.clientX - fingerDownPos.x);
  const dy = Math.abs(t.clientY - fingerDownPos.y);
  const dt = Date.now() - fingerDownTime;
  fingerDownPos = null;
  
  // Was it a scroll or long press?
  if (dx > TAP_MOVE_THRESHOLD || dy > TAP_MOVE_THRESHOLD || dt > TAP_TIME_THRESHOLD) return;
  
  // It's a genuine TAP — check for double-tap
  const now = Date.now();
  if (now - lastFingerTap < 400) {
    state.stepCtrl.prev();
    lastFingerTap = 0;
    return;
  }
  lastFingerTap = now;
  setTimeout(() => {
    if (lastFingerTap !== 0 && Date.now() - lastFingerTap >= 380) {
      state.stepCtrl.next();
    }
  }, 400);
}, { passive: true });

// Mouse click = next step (only when no draw tool active)
document.getElementById('notebookContent').addEventListener('click', (e) => {
  if (!state.stepCtrl) return;
  if (isToolActive()) return;
  if (isPenActive()) return;
  state.stepCtrl.next();
});

// Mouse double-click = go back one step (only when no drawing tool active)
document.getElementById('notebookContent').addEventListener('dblclick', (e) => {
  if (!state.stepCtrl) return;
  if (isToolActive()) return;
  e.preventDefault();
  state.stepCtrl.prev();
});

// Menu toggles
document.getElementById('menuToggle').addEventListener('click', (e) => {
  e.stopPropagation();
  document.getElementById('exerciseNav').classList.toggle('open');
});
document.getElementById('btnMenu').addEventListener('click', (e) => {
  e.stopPropagation();
  document.getElementById('exerciseNav').classList.toggle('open');
});
// Bottom-bar undo/redo buttons
document.getElementById('btnUndo').addEventListener('click', (e) => {
  e.stopPropagation();
  undoAnnotation();
});
document.getElementById('btnRedo').addEventListener('click', (e) => {
  e.stopPropagation();
  redoAnnotation();
});

// Click outside nav to close
document.addEventListener('click', (e) => {
  const nav = document.getElementById('exerciseNav');
  const toggle = document.getElementById('menuToggle');
  const btn = document.getElementById('btnMenu');
  if (nav.classList.contains('open') && !nav.contains(e.target)
      && e.target !== toggle && e.target !== btn) {
    nav.classList.remove('open');
  }
});

// Keyboard
document.addEventListener('keydown', (e) => {
  if (!state.stepCtrl) return;
  if (e.target.tagName === 'TEXTAREA' || e.target.tagName === 'INPUT') return;

  switch (e.key) {
    case 'ArrowRight':
    case 'Enter':
      e.preventDefault();
      state.stepCtrl.next();
      break;
    case ' ':
      e.preventDefault();
      if (e.shiftKey) {
        state.stepCtrl.prev();  // Shift+Space = back
      } else {
        state.stepCtrl.next();  // Space = forward
      }
      break;
    case 'ArrowLeft':
    case 'Backspace':
      e.preventDefault();
      state.stepCtrl.prev();
      break;
    case 'r':
    case 'R':
      e.preventDefault();
      state.stepCtrl.reset();
      document.getElementById('notebookContent').scrollTop = 0;
      break;
    case 'Escape':
      document.getElementById('exerciseNav').classList.remove('open');
      break;
  }
});

// Touch swipe (finger swipe navigates regardless of tool)
let touchStartX = 0;
let touchStartY = 0;
document.addEventListener('touchstart', (e) => {
  if (e.touches.length !== 1) return;
  const t = e.touches[0];
  if (t.touchType === 'stylus') return; // IGNORING APPLE PENCIL
  touchStartX = t.clientX;
  touchStartY = t.clientY;
});
document.addEventListener('touchend', (e) => {
  if (e.changedTouches.length !== 1) return;
  const t = e.changedTouches[0];
  if (t.touchType === 'stylus') return; // IGNORING APPLE PENCIL
  
  const dx = t.clientX - touchStartX;
  const dy = t.clientY - touchStartY;
  // Only swipe if horizontal movement is dominant
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) {
    if (dx < 0 && state.stepCtrl) state.stepCtrl.next();
    if (dx > 0 && state.stepCtrl) state.stepCtrl.prev();
  }
});

// ─── BOOT ───
init();
